import type { MenuItem, Restaurant } from "@/types/dining";

const unsplash = (id: string, width = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=80`;

const slug = "shagun";

function dish(
  item: Omit<MenuItem, "restaurantSlug" | "available"> & { available?: boolean },
): MenuItem {
  return {
    restaurantSlug: slug,
    available: item.available ?? true,
    ...item,
  };
}

export const restaurants: Restaurant[] = [
  {
    slug,
    name: "Shagun",
    tagline: "Good food. Happy table.",
    description:
      "Order from your phone. We will bring the food to your table.",
    logo: "/brands/shagun-logo.jpg",
    coverImage: unsplash("photo-1552566626-52f8b828add9", 1800),
    ambienceImage: unsplash("photo-1517248135467-4c7edcad34c4", 1600),
    cuisine: "North Indian, South Indian & Chinese",
    location: "Civil Lines, Kanpur",
    hours: "11:00 am — 11:00 pm",
    loyaltyProgramName: "Shagun Rewards",
    loyaltyTagline: "Eat more. Get free food next time.",
    taxRate: 0.05,
    estimatedPrepMinutes: 22,
    theme: {
      mode: "dark",
      radius: "1.15rem",
      fonts: { heading: "playfair", sans: "karla" },
      colors: {
        background: "#16080C",
        foreground: "#F7EFE6",
        card: "#221016",
        cardForeground: "#F7EFE6",
        popover: "#2A141A",
        popoverForeground: "#F7EFE6",
        primary: "#D4A85A",
        primaryForeground: "#1A0C0A",
        secondary: "#2E171C",
        secondaryForeground: "#F7EFE6",
        muted: "#261218",
        mutedForeground: "#D4C4B4",
        accent: "#9B2C3A",
        accentForeground: "#FFF8F1",
        destructive: "#E06A5A",
        border: "rgba(212, 168, 90, 0.22)",
        input: "rgba(212, 168, 90, 0.26)",
        ring: "#D4A85A",
      },
    },
    categories: [
      {
        id: "starters",
        slug: "starters",
        name: "Starters",
        nameHi: "स्टार्टर",
        description: "Small plates to begin.",
        image: unsplash("photo-1601050690597-df0568f70950"),
      },
      {
        id: "north-indian",
        slug: "north-indian",
        name: "North Indian",
        nameHi: "नॉर्थ इंडियन",
        description: "Curry, roti, and biryani.",
        image: unsplash("photo-1565557623262-b51c2513a641"),
      },
      {
        id: "south-indian",
        slug: "south-indian",
        name: "South Indian",
        nameHi: "साउथ इंडियन",
        description: "Dosa, idli, and sambar.",
        image: unsplash("photo-1630383249896-424e482df921"),
      },
      {
        id: "chinese",
        slug: "chinese",
        name: "Chinese",
        nameHi: "चाइनीज़",
        description: "Noodles, fried rice, and chilli dishes.",
        image: unsplash("photo-1585032226651-759b368d7246"),
      },
      {
        id: "desserts",
        slug: "desserts",
        name: "Desserts",
        nameHi: "मिठाई",
        description: "Sweets after the meal.",
        image: unsplash("photo-1618164436241-4473940d1f5c"),
      },
      {
        id: "drinks",
        slug: "drinks",
        name: "Drinks",
        nameHi: "ड्रिंक्स",
        description: "Tea, lassi, and cold drinks.",
        image: unsplash("photo-1571934811356-5cc061b6821f"),
      },
      {
        id: "combos",
        slug: "combos",
        name: "Combos",
        nameHi: "कॉम्बो",
        description: "Full meals at a better price.",
        image: unsplash("photo-1585937421612-70a008356fbe"),
      },
    ],
    menuItems: [
      dish({
        id: "veg-samosa",
        categoryId: "starters",
        name: "Veg Samosa",
        description: "Crispy pastry with potato and peas. 2 pieces.",
        ingredients: ["Potato", "Peas", "Cumin", "Wheat flour"],
        price: 89,
        image: unsplash("photo-1601050690597-df0568f70950"),
        diet: "veg",
        popular: true,
      }),
      dish({
        id: "paneer-tikka",
        categoryId: "starters",
        name: "Paneer Tikka",
        description: "Cottage cheese roasted in the tandoor, with mint chutney.",
        ingredients: ["Paneer", "Yogurt", "Spices", "Capsicum", "Mint chutney"],
        price: 249,
        image: unsplash("photo-1567188040759-fb8a883dc6d8"),
        diet: "veg",
        popular: true,
        chefPick: true,
        tags: ["Tandoor"],
      }),
      dish({
        id: "chicken-tikka",
        categoryId: "starters",
        name: "Chicken Tikka",
        description: "Soft chicken pieces roasted with spices.",
        ingredients: ["Chicken", "Yogurt", "Spices"],
        price: 279,
        image: unsplash("photo-1599487488170-d11ec9c172f0"),
        diet: "non-veg",
        popular: true,
      }),
      dish({
        id: "honey-chilli-potato",
        categoryId: "starters",
        name: "Honey Chilli Potato",
        description: "Crispy potato with sweet and spicy sauce.",
        ingredients: ["Potato", "Honey", "Chilli", "Sesame"],
        price: 179,
        image: unsplash("photo-1573080496219-bb080dd4f877"),
        diet: "veg",
      }),
      dish({
        id: "veg-spring-roll",
        categoryId: "starters",
        name: "Veg Spring Roll",
        description: "Crispy rolls filled with mixed vegetables. 4 pieces.",
        ingredients: ["Cabbage", "Carrot", "Wrapper", "Chilli sauce"],
        price: 159,
        image: unsplash("photo-1496116218417-1a781b1c416c"),
        diet: "veg",
      }),
      dish({
        id: "butter-chicken",
        categoryId: "north-indian",
        name: "Butter Chicken",
        description: "Chicken in a creamy tomato gravy. Not too spicy.",
        ingredients: ["Chicken", "Tomato", "Butter", "Cream", "Spices"],
        price: 349,
        image: unsplash("photo-1565557623262-b51c2513a641"),
        diet: "non-veg",
        popular: true,
        chefPick: true,
        customizations: [
          {
            id: "spice",
            name: "How spicy?",
            type: "single",
            required: true,
            options: [
              { id: "mild", name: "Less spicy", priceDelta: 0 },
              { id: "medium", name: "Medium", priceDelta: 0 },
              { id: "hot", name: "Spicy", priceDelta: 0 },
            ],
          },
        ],
      }),
      dish({
        id: "paneer-butter-masala",
        categoryId: "north-indian",
        name: "Paneer Butter Masala",
        description: "Soft paneer in a rich tomato gravy.",
        ingredients: ["Paneer", "Tomato", "Butter", "Cream"],
        price: 299,
        image: unsplash("photo-1631452180519-c014fe946bc7"),
        diet: "veg",
        popular: true,
        customizations: [
          {
            id: "spice",
            name: "How spicy?",
            type: "single",
            required: true,
            options: [
              { id: "mild", name: "Less spicy", priceDelta: 0 },
              { id: "medium", name: "Medium", priceDelta: 0 },
              { id: "hot", name: "Spicy", priceDelta: 0 },
            ],
          },
        ],
      }),
      dish({
        id: "dal-makhani",
        categoryId: "north-indian",
        name: "Dal Makhani",
        description: "Black dal cooked slowly with butter and cream.",
        ingredients: ["Black dal", "Butter", "Cream", "Tomato"],
        price: 229,
        image: unsplash("photo-1546833999-b9f581a1996d"),
        diet: "veg",
      }),
      dish({
        id: "palak-paneer",
        categoryId: "north-indian",
        name: "Palak Paneer",
        description: "Paneer cubes in a smooth spinach gravy.",
        ingredients: ["Paneer", "Spinach", "Garlic", "Cream"],
        price: 269,
        image: unsplash("photo-1505253758473-96b7015fcd40"),
        diet: "veg",
      }),
      dish({
        id: "chicken-biryani",
        categoryId: "north-indian",
        name: "Chicken Biryani",
        description: "Rice and chicken cooked with whole spices.",
        ingredients: ["Basmati rice", "Chicken", "Spices", "Mint"],
        price: 329,
        image: unsplash("photo-1589302168068-964664d93dc0"),
        diet: "non-veg",
        popular: true,
        customizations: [
          {
            id: "extras",
            name: "Add extra",
            type: "multiple",
            required: false,
            options: [
              { id: "raita", name: "Raita", priceDelta: 30 },
              { id: "salan", name: "Extra gravy", priceDelta: 40 },
            ],
          },
        ],
      }),
      dish({
        id: "veg-biryani",
        categoryId: "north-indian",
        name: "Veg Biryani",
        description: "Rice cooked with mixed vegetables and spices.",
        ingredients: ["Basmati rice", "Mixed vegetables", "Spices"],
        price: 279,
        image: unsplash("photo-1563379091339-03b21ab4a4f8"),
        diet: "veg",
        customizations: [
          {
            id: "extras",
            name: "Add extra",
            type: "multiple",
            required: false,
            options: [
              { id: "raita", name: "Raita", priceDelta: 30 },
              { id: "salan", name: "Extra gravy", priceDelta: 40 },
            ],
          },
        ],
      }),
      dish({
        id: "chole-bhature",
        categoryId: "north-indian",
        name: "Chole Bhature",
        description: "Spicy chole with 2 soft bhature.",
        ingredients: ["Chickpeas", "Bhature", "Onion", "Pickle"],
        price: 199,
        image: unsplash("photo-1626132647523-66f5bf380027"),
        diet: "veg",
        popular: true,
      }),
      dish({
        id: "butter-naan",
        categoryId: "north-indian",
        name: "Butter Naan",
        description: "Soft tandoor bread with butter. 1 piece.",
        ingredients: ["Flour", "Butter", "Yogurt"],
        price: 49,
        image: unsplash("photo-1606491956689-2ea866880c84"),
        diet: "veg",
      }),
      dish({
        id: "masala-dosa",
        categoryId: "south-indian",
        name: "Masala Dosa",
        description: "Crispy dosa with potato filling, sambar and chutney.",
        ingredients: ["Rice batter", "Potato", "Sambar", "Coconut chutney"],
        price: 149,
        image: unsplash("photo-1630383249896-424e482df921"),
        diet: "veg",
        popular: true,
        chefPick: true,
        customizations: [
          {
            id: "extras",
            name: "Add extra",
            type: "multiple",
            required: false,
            options: [
              { id: "sambar", name: "Extra sambar", priceDelta: 20 },
              { id: "cheese", name: "Cheese", priceDelta: 30 },
            ],
          },
        ],
      }),
      dish({
        id: "idli-sambar",
        categoryId: "south-indian",
        name: "Idli Sambar",
        description: "Soft idli with hot sambar and chutney. 4 pieces.",
        ingredients: ["Idli", "Sambar", "Coconut chutney"],
        price: 119,
        image: unsplash("photo-1589301760014-d929f3979dbc"),
        diet: "veg",
        popular: true,
      }),
      dish({
        id: "medu-vada",
        categoryId: "south-indian",
        name: "Medu Vada",
        description: "Crispy lentil vada with sambar. 2 pieces.",
        ingredients: ["Urad dal", "Sambar", "Coconut chutney"],
        price: 99,
        image: unsplash("photo-1668236543090-82eba5ee5976"),
        diet: "veg",
      }),
      dish({
        id: "onion-uttapam",
        categoryId: "south-indian",
        name: "Onion Uttapam",
        description: "Thick dosa with onion on top. Served with sambar.",
        ingredients: ["Rice batter", "Onion", "Sambar", "Chutney"],
        price: 139,
        image: unsplash("photo-1668236543090-82eba5ee5976"),
        diet: "veg",
      }),
      dish({
        id: "hakka-noodles",
        categoryId: "chinese",
        name: "Veg Hakka Noodles",
        description: "Noodles tossed with vegetables.",
        ingredients: ["Noodles", "Cabbage", "Capsicum", "Soy sauce"],
        price: 189,
        image: unsplash("photo-1585032226651-759b368d7246"),
        diet: "veg",
        popular: true,
        customizations: [
          {
            id: "spice",
            name: "How spicy?",
            type: "single",
            required: true,
            options: [
              { id: "mild", name: "Less spicy", priceDelta: 0 },
              { id: "medium", name: "Medium", priceDelta: 0 },
              { id: "hot", name: "Spicy", priceDelta: 0 },
            ],
          },
        ],
      }),
      dish({
        id: "chicken-fried-rice",
        categoryId: "chinese",
        name: "Chicken Fried Rice",
        description: "Rice tossed with chicken and vegetables.",
        ingredients: ["Rice", "Chicken", "Egg", "Soy sauce"],
        price: 219,
        image: unsplash("photo-1603133872878-684f208fb84b"),
        diet: "non-veg",
      }),
      dish({
        id: "chilli-paneer",
        categoryId: "chinese",
        name: "Chilli Paneer",
        description: "Paneer in a spicy Chinese sauce.",
        ingredients: ["Paneer", "Capsicum", "Onion", "Chilli sauce"],
        price: 229,
        image: unsplash("photo-1626074353765-517a681e40be"),
        diet: "veg",
        chefPick: true,
      }),
      dish({
        id: "veg-manchurian",
        categoryId: "chinese",
        name: "Veg Manchurian",
        description: "Vegetable balls in a tangy gravy.",
        ingredients: ["Cabbage", "Carrot", "Soy sauce", "Garlic"],
        price: 199,
        image: unsplash("photo-1512621776951-a57141f2eefd"),
        diet: "veg",
      }),
      dish({
        id: "chicken-momos",
        categoryId: "chinese",
        name: "Chicken Momos",
        description: "Steamed dumplings with chicken filling. 8 pieces.",
        ingredients: ["Chicken", "Wrapper", "Garlic chutney"],
        price: 169,
        image: unsplash("photo-1563245372-f21724e3856d"),
        diet: "non-veg",
        popular: true,
        customizations: [
          {
            id: "style",
            name: "How do you want them?",
            type: "single",
            required: true,
            options: [
              { id: "steamed", name: "Steamed", priceDelta: 0 },
              { id: "fried", name: "Fried", priceDelta: 20 },
            ],
          },
        ],
      }),
      dish({
        id: "gulab-jamun",
        categoryId: "desserts",
        name: "Gulab Jamun",
        description: "Soft sweet balls in sugar syrup. 2 pieces.",
        ingredients: ["Milk solids", "Sugar syrup", "Cardamom"],
        price: 99,
        image: unsplash("photo-1618164436241-4473940d1f5c"),
        diet: "veg",
        popular: true,
      }),
      dish({
        id: "rasmalai",
        categoryId: "desserts",
        name: "Rasmalai",
        description: "Soft paneer discs in sweet flavoured milk. 2 pieces.",
        ingredients: ["Paneer", "Milk", "Saffron", "Pista"],
        price: 119,
        image: unsplash("photo-1488477181946-6428a0291777"),
        diet: "veg",
        chefPick: true,
      }),
      dish({
        id: "gajar-halwa",
        categoryId: "desserts",
        name: "Gajar ka Halwa",
        description: "Warm carrot dessert with dry fruits.",
        ingredients: ["Carrot", "Milk", "Ghee", "Dry fruits"],
        price: 129,
        image: unsplash("photo-1571115177098-24ec42ed204d"),
        diet: "veg",
      }),
      dish({
        id: "ice-cream",
        categoryId: "desserts",
        name: "Ice Cream",
        description: "Two scoops. Ask the waiter for today’s flavours.",
        ingredients: ["Milk", "Sugar", "Flavour"],
        price: 89,
        image: unsplash("photo-1563805042-7684c019e1cb"),
        diet: "veg",
      }),
      dish({
        id: "masala-chai",
        categoryId: "drinks",
        name: "Masala Chai",
        description: "Hot tea with milk and spices.",
        ingredients: ["Tea", "Milk", "Ginger", "Cardamom"],
        price: 49,
        image: unsplash("photo-1571934811356-5cc061b6821f"),
        diet: "veg",
        popular: true,
      }),
      dish({
        id: "mango-lassi",
        categoryId: "drinks",
        name: "Mango Lassi",
        description: "Sweet yogurt drink with mango.",
        ingredients: ["Yogurt", "Mango", "Sugar"],
        price: 99,
        image: unsplash("photo-1546173159-315724a31696"),
        diet: "veg",
        popular: true,
      }),
      dish({
        id: "lime-soda",
        categoryId: "drinks",
        name: "Fresh Lime Soda",
        description: "Fresh lime with soda. Sweet or salted.",
        ingredients: ["Lime", "Soda", "Sugar or salt"],
        price: 69,
        image: unsplash("photo-1513558161293-cdaf765ed2fd"),
        diet: "veg",
        customizations: [
          {
            id: "style",
            name: "Sweet or salted?",
            type: "single",
            required: true,
            options: [
              { id: "sweet", name: "Sweet", priceDelta: 0 },
              { id: "salted", name: "Salted", priceDelta: 0 },
              { id: "mixed", name: "Mixed", priceDelta: 0 },
            ],
          },
        ],
      }),
      dish({
        id: "cold-coffee",
        categoryId: "drinks",
        name: "Cold Coffee",
        description: "Coffee shaken with milk and ice.",
        ingredients: ["Coffee", "Milk", "Ice", "Sugar"],
        price: 119,
        image: unsplash("photo-1461023058943-07fcbe16d735"),
        diet: "veg",
      }),
      dish({
        id: "filter-coffee",
        categoryId: "drinks",
        name: "Filter Coffee",
        description: "South Indian coffee with milk.",
        ingredients: ["Filter coffee", "Milk", "Sugar"],
        price: 79,
        image: unsplash("photo-1495474472287-4d71bcdd2085"),
        diet: "veg",
      }),
      dish({
        id: "north-thali",
        categoryId: "combos",
        name: "Shagun Veg Thali",
        description: "Dal, paneer, roti, rice, salad and sweet. Save ₹40.",
        ingredients: ["Dal Makhani", "Paneer", "Roti", "Rice", "Sweet"],
        price: 349,
        image: unsplash("photo-1585937421612-70a008356fbe"),
        diet: "veg",
        popular: true,
        tags: ["Save ₹40"],
      }),
      dish({
        id: "south-combo",
        categoryId: "combos",
        name: "South Indian Combo",
        description: "Masala dosa, 2 idli and filter coffee. Save ₹30.",
        ingredients: ["Masala Dosa", "Idli", "Filter Coffee"],
        price: 229,
        image: unsplash("photo-1589301760014-d929f3979dbc"),
        diet: "veg",
        tags: ["Save ₹30"],
      }),
      dish({
        id: "chinese-combo",
        categoryId: "combos",
        name: "Chinese Combo",
        description: "Hakka noodles, chilli paneer and lime soda. Save ₹40.",
        ingredients: ["Hakka Noodles", "Chilli Paneer", "Lime Soda"],
        price: 299,
        image: unsplash("photo-1585032226651-759b368d7246"),
        diet: "veg",
        tags: ["Save ₹40"],
      }),
      dish({
        id: "butter-chicken-thali",
        categoryId: "combos",
        name: "Butter Chicken Thali",
        description: "Butter chicken, dal, naan, rice and sweet. Save ₹50.",
        ingredients: ["Butter Chicken", "Dal", "Naan", "Rice", "Sweet"],
        price: 399,
        image: unsplash("photo-1565557623262-b51c2513a641"),
        diet: "non-veg",
        tags: ["Save ₹50"],
      }),
    ],
  },
];

export const restaurantMap = Object.fromEntries(
  restaurants.map((restaurant) => [restaurant.slug, restaurant]),
) as Record<string, Restaurant>;
