import type { Restaurant } from "@/types/dining";

const unsplash = (id: string, width = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=80`;

export const restaurants: Restaurant[] = [
  {
    slug: "abc-lounge",
    name: "ABC Lounge",
    tagline: "Premium dining experience",
    description:
      "Low light, unhurried plates, and service that never interrupts the conversation. An evening house for guests who prefer the room to feel like a private club.",
    logo: "/brands/abc-lounge.svg",
    coverImage: unsplash("photo-1517248135467-4c7edcad34c4", 1800),
    ambienceImage: unsplash("photo-1559339352-11d035aa65de", 1600),
    cuisine: "Contemporary Indian & Continental",
    location: "Bandra West, Mumbai",
    hours: "12:00 pm — 1:00 am",
    loyaltyProgramName: "ABC Rewards",
    loyaltyTagline: "Earn points on every purchase",
    taxRate: 0.05,
    estimatedPrepMinutes: 20,
    theme: {
      mode: "dark",
      radius: "1.15rem",
      fonts: { heading: "cormorant", sans: "outfit" },
      colors: {
        background: "#100c09",
        foreground: "#f6efe4",
        card: "#1a1410",
        cardForeground: "#f6efe4",
        popover: "#201913",
        popoverForeground: "#f6efe4",
        primary: "#c9a46a",
        primaryForeground: "#1a140c",
        secondary: "#2a221b",
        secondaryForeground: "#f6efe4",
        muted: "#241c16",
        mutedForeground: "#b7a594",
        accent: "#d7b57a",
        accentForeground: "#1a140c",
        destructive: "#d47361",
        border: "rgba(201, 164, 106, 0.18)",
        input: "rgba(201, 164, 106, 0.22)",
        ring: "#c9a46a",
      },
    },
    categories: [
      {
        id: "food",
        slug: "food",
        name: "Food",
        description: "Plates meant to be shared slowly.",
        image: unsplash("photo-1544025162-d76694265947"),
      },
      {
        id: "drinks",
        slug: "drinks",
        name: "Drinks",
        description: "House pours and late-evening glasses.",
        image: unsplash("photo-1514362545857-3bc16c4c7d1b"),
      },
      {
        id: "desserts",
        slug: "desserts",
        name: "Desserts",
        description: "A last course worth lingering over.",
        image: unsplash("photo-1606313564200-e75d5e30476c"),
      },
      {
        id: "combos",
        slug: "combos",
        name: "Combos",
        description: "Considered pairings, quietly priced.",
        image: unsplash("photo-1550547660-d9450f859349"),
      },
    ],
    menuItems: [
      {
        id: "farmhouse-pizza",
        restaurantSlug: "abc-lounge",
        categoryId: "food",
        name: "Farmhouse Pizza",
        description:
          "Wood-fired crust, blistered vegetables, and a slow stretch of mozzarella.",
        ingredients: [
          "San Marzano tomato",
          "Mozzarella",
          "Bell pepper",
          "Mushroom",
          "Onion",
          "Olive oil",
        ],
        price: 399,
        image: unsplash("photo-1565299624946-b28f40a0ae38"),
        diet: "veg",
        available: true,
        popular: true,
        chefPick: true,
        tags: ["Signature"],
        customizations: [
          {
            id: "size",
            name: "Pizza Size",
            type: "single",
            required: true,
            options: [
              { id: "regular", name: "Regular", priceDelta: 0 },
              { id: "medium", name: "Medium", priceDelta: 80 },
              { id: "large", name: "Large", priceDelta: 160 },
            ],
          },
          {
            id: "addons",
            name: "Add-ons",
            type: "multiple",
            required: false,
            options: [
              { id: "extra-cheese", name: "Extra Cheese", priceDelta: 40 },
              { id: "jalapeno", name: "Jalapeno", priceDelta: 20 },
            ],
          },
        ],
      },
      {
        id: "paneer-tikka",
        restaurantSlug: "abc-lounge",
        categoryId: "food",
        name: "Paneer Tikka Platter",
        description:
          "Charred cottage cheese, smoked yoghurt, and a hush of kasuri methi.",
        ingredients: ["Paneer", "Hung curd", "Kashmiri chilli", "Peppers", "Mint chutney"],
        price: 349,
        image: unsplash("photo-1567188040759-fb8a883dc6d8"),
        diet: "veg",
        available: true,
        popular: true,
        tags: ["Tandoor"],
      },
      {
        id: "truffle-risotto",
        restaurantSlug: "abc-lounge",
        categoryId: "food",
        name: "Truffle Mushroom Risotto",
        description:
          "Carnaroli rice finished with black truffle butter and aged parmesan.",
        ingredients: ["Carnaroli rice", "Wild mushrooms", "Truffle butter", "Parmesan"],
        price: 459,
        image: unsplash("photo-1476124369491-e7addf5db371"),
        diet: "veg",
        available: true,
        chefPick: true,
      },
      {
        id: "charred-tenderloin",
        restaurantSlug: "abc-lounge",
        categoryId: "food",
        name: "Charred Tenderloin",
        description:
          "Pepper-crusted beef, bone marrow butter, and roasted garlic mash.",
        ingredients: ["Tenderloin", "Black pepper", "Bone marrow butter", "Potato"],
        price: 799,
        image: unsplash("photo-1544025162-d76694265947"),
        diet: "non-veg",
        available: true,
        tags: ["Evening"],
      },
      {
        id: "lounge-burger",
        restaurantSlug: "abc-lounge",
        categoryId: "food",
        name: "Lounge Burger",
        description:
          "A quiet, serious burger — aged cheddar, caramelised onion, brioche.",
        ingredients: ["Beef patty", "Aged cheddar", "Onion jam", "Brioche"],
        price: 379,
        image: unsplash("photo-1568901346375-23c9450c58cd"),
        diet: "non-veg",
        available: true,
      },
      {
        id: "cheese-fries",
        restaurantSlug: "abc-lounge",
        categoryId: "food",
        name: "Cheese Fries",
        description: "Crisp russet fries under a warm fold of aged cheddar sauce.",
        ingredients: ["Potato", "Cheddar sauce", "Chives", "Smoked salt"],
        price: 99,
        image: unsplash("photo-1573080496219-bb080dd4f877"),
        diet: "veg",
        available: true,
        popular: true,
      },
      {
        id: "cold-coffee",
        restaurantSlug: "abc-lounge",
        categoryId: "drinks",
        name: "Cold Coffee",
        description: "House espresso shaken over ice with cold milk and vanilla.",
        ingredients: ["Espresso", "Milk", "Vanilla", "Ice"],
        price: 120,
        image: unsplash("photo-1461023058943-07fcbe16d735"),
        diet: "veg",
        available: true,
        popular: true,
      },
      {
        id: "espresso-martini",
        restaurantSlug: "abc-lounge",
        categoryId: "drinks",
        name: "Signature Espresso Martini",
        description: "Vodka, fresh espresso, and a velvet crema.",
        ingredients: ["Vodka", "Espresso", "Coffee liqueur"],
        price: 420,
        image: unsplash("photo-1545438102-799c3991ffb2"),
        diet: "veg",
        available: true,
        chefPick: true,
        tags: ["Bar"],
      },
      {
        id: "lime-cooler",
        restaurantSlug: "abc-lounge",
        categoryId: "drinks",
        name: "Fresh Lime Cooler",
        description: "Pressed lime, soda, a pinch of black salt.",
        ingredients: ["Lime", "Soda", "Black salt", "Mint"],
        price: 90,
        image: unsplash("photo-1513558161293-cdaf765ed2fd"),
        diet: "veg",
        available: true,
      },
      {
        id: "old-fashioned",
        restaurantSlug: "abc-lounge",
        categoryId: "drinks",
        name: "Old Fashioned",
        description: "Bourbon, demerara, and an orange oil finish.",
        ingredients: ["Bourbon", "Demerara", "Angostura", "Orange"],
        price: 450,
        image: unsplash("photo-1470337458703-46ad1756a187"),
        diet: "veg",
        available: true,
      },
      {
        id: "chocolate-fondant",
        restaurantSlug: "abc-lounge",
        categoryId: "desserts",
        name: "Dark Chocolate Fondant",
        description: "A warm centre, sea salt, and vanilla bean cream.",
        ingredients: ["Dark chocolate", "Butter", "Eggs", "Vanilla cream"],
        price: 280,
        image: unsplash("photo-1606313564200-e75d5e30476c"),
        diet: "veg",
        available: true,
        chefPick: true,
      },
      {
        id: "basque-cheesecake",
        restaurantSlug: "abc-lounge",
        categoryId: "desserts",
        name: "Basque Cheesecake",
        description: "Burnt top, custard heart. Tonight's bake is spoken for.",
        ingredients: ["Cream cheese", "Cream", "Eggs", "Sugar"],
        price: 260,
        image: unsplash("photo-1533134486753-c833f0ed4866"),
        diet: "veg",
        available: false,
      },
      {
        id: "affogato",
        restaurantSlug: "abc-lounge",
        categoryId: "desserts",
        name: "Vanilla Affogato",
        description: "Gelato quietly undone by a shot of espresso.",
        ingredients: ["Vanilla gelato", "Espresso"],
        price: 190,
        image: unsplash("photo-1414235077428-338989a2e8c0"),
        diet: "veg",
        available: true,
      },
      {
        id: "pizza-coffee-combo",
        restaurantSlug: "abc-lounge",
        categoryId: "combos",
        name: "Pizza Evening Combo",
        description: "Farmhouse Pizza with Cold Coffee. Save ₹40.",
        ingredients: ["Farmhouse Pizza", "Cold Coffee"],
        price: 479,
        image: unsplash("photo-1550547660-d9450f859349"),
        diet: "veg",
        available: true,
        popular: true,
        tags: ["Save ₹40"],
      },
      {
        id: "burger-plate-combo",
        restaurantSlug: "abc-lounge",
        categoryId: "combos",
        name: "Burger Evening Plate",
        description: "Lounge Burger, cheese fries, and a lime cooler.",
        ingredients: ["Lounge Burger", "Cheese Fries", "Fresh Lime Cooler"],
        price: 519,
        image: unsplash("photo-1550547660-d9450f859349"),
        diet: "non-veg",
        available: true,
        tags: ["Save ₹49"],
      },
    ],
  },
  {
    slug: "cafe-xyz",
    name: "Cafe XYZ",
    tagline: "Slow mornings. Honest food.",
    description:
      "A sunlit specialty cafe for careful pours, warm bread, and tables that invite you to stay longer than you planned.",
    logo: "/brands/cafe-xyz.svg",
    coverImage: unsplash("photo-1495474472287-4d71bcdd2085", 1800),
    ambienceImage: unsplash("photo-1501339847302-ac426a4a7cbb", 1600),
    cuisine: "Specialty coffee & all-day brunch",
    location: "Koramangala, Bengaluru",
    hours: "8:00 am — 10:00 pm",
    loyaltyProgramName: "XYZ Club",
    loyaltyTagline: "Stamps for the regulars. Quietly generous.",
    taxRate: 0.05,
    estimatedPrepMinutes: 14,
    theme: {
      mode: "light",
      radius: "1.25rem",
      fonts: { heading: "fraunces", sans: "dm-sans" },
      colors: {
        background: "#f4ebe0",
        foreground: "#2a1c14",
        card: "#fffaf3",
        cardForeground: "#2a1c14",
        popover: "#fffaf3",
        popoverForeground: "#2a1c14",
        primary: "#9c3d2e",
        primaryForeground: "#fff8f1",
        secondary: "#efe2d1",
        secondaryForeground: "#2a1c14",
        muted: "#eadccb",
        mutedForeground: "#6d5646",
        accent: "#c4784a",
        accentForeground: "#fff8f1",
        destructive: "#b42318",
        border: "rgba(42, 28, 20, 0.12)",
        input: "rgba(42, 28, 20, 0.14)",
        ring: "#9c3d2e",
      },
    },
    categories: [
      {
        id: "food",
        slug: "food",
        name: "Food",
        description: "Brunch plates and warm toast.",
        image: unsplash("photo-1482049016688-2d3e1b311543"),
      },
      {
        id: "drinks",
        slug: "drinks",
        name: "Drinks",
        description: "Single origin pours and house chai.",
        image: unsplash("photo-1495474472287-4d71bcdd2085"),
      },
      {
        id: "desserts",
        slug: "desserts",
        name: "Desserts",
        description: "Pastry from the morning bake.",
        image: unsplash("photo-1509440159596-0249088772ff"),
      },
      {
        id: "combos",
        slug: "combos",
        name: "Combos",
        description: "The usual, already decided.",
        image: unsplash("photo-1495474472287-4d71bcdd2085"),
      },
    ],
    menuItems: [
      {
        id: "avocado-toast",
        restaurantSlug: "cafe-xyz",
        categoryId: "food",
        name: "Avocado Toast",
        description: "Sourdough, crushed avocado, chilli oil, and lemon zest.",
        ingredients: ["Sourdough", "Avocado", "Chilli oil", "Lemon"],
        price: 280,
        image: unsplash("photo-1541519227354-08fa5d50c44d"),
        diet: "veg",
        available: true,
        popular: true,
        chefPick: true,
      },
      {
        id: "shakshuka",
        restaurantSlug: "cafe-xyz",
        categoryId: "food",
        name: "Shakshuka",
        description: "Eggs in a slow tomato sauce with warm pita.",
        ingredients: ["Eggs", "Tomato", "Peppers", "Cumin", "Pita"],
        price: 320,
        image: unsplash("photo-1590412200988-a436970781fa"),
        diet: "egg",
        available: true,
        popular: true,
      },
      {
        id: "mushroom-toastie",
        restaurantSlug: "cafe-xyz",
        categoryId: "food",
        name: "Mushroom Toastie",
        description: "Gruyère, thyme mushrooms, and browned butter.",
        ingredients: ["Gruyère", "Mushrooms", "Thyme", "Sourdough"],
        price: 300,
        image: unsplash("photo-1528736235302-52922df5c122"),
        diet: "veg",
        available: true,
      },
      {
        id: "seasonal-bowl",
        restaurantSlug: "cafe-xyz",
        categoryId: "food",
        name: "Seasonal Grain Bowl",
        description: "Farro, roasted squash, herbs, and a tahini dressing.",
        ingredients: ["Farro", "Squash", "Tahini", "Herbs"],
        price: 340,
        image: unsplash("photo-1512621776951-a57141f2eefd"),
        diet: "veg",
        available: true,
      },
      {
        id: "pour-over",
        restaurantSlug: "cafe-xyz",
        categoryId: "drinks",
        name: "Single Origin Pour Over",
        description: "A clean cup. Today's lot is from Chikmagalur.",
        ingredients: ["Single origin coffee"],
        price: 180,
        image: unsplash("photo-1495474472287-4d71bcdd2085"),
        diet: "veg",
        available: true,
        chefPick: true,
        customizations: [
          {
            id: "size",
            name: "Cup size",
            type: "single",
            required: true,
            options: [
              { id: "regular", name: "Regular", priceDelta: 0 },
              { id: "large", name: "Large", priceDelta: 30 },
            ],
          },
        ],
      },
      {
        id: "oat-latte",
        restaurantSlug: "cafe-xyz",
        categoryId: "drinks",
        name: "Oat Latte",
        description: "House espresso with steamed oat, lightly sweet.",
        ingredients: ["Espresso", "Oat milk"],
        price: 210,
        image: unsplash("photo-1461023058943-07fcbe16d735"),
        diet: "veg",
        available: true,
        popular: true,
      },
      {
        id: "cold-brew",
        restaurantSlug: "cafe-xyz",
        categoryId: "drinks",
        name: "Cold Brew",
        description: "Sixteen hours, served over a single cube.",
        ingredients: ["Cold brew coffee"],
        price: 190,
        image: unsplash("photo-1517701604599-bb29b565090c"),
        diet: "veg",
        available: true,
      },
      {
        id: "house-chai",
        restaurantSlug: "cafe-xyz",
        categoryId: "drinks",
        name: "House Chai",
        description: "Cardamom-forward, reduced milk, no rush.",
        ingredients: ["Assam tea", "Cardamom", "Ginger", "Milk"],
        price: 90,
        image: unsplash("photo-1571934811356-5cc061b6821f"),
        diet: "veg",
        available: true,
      },
      {
        id: "almond-croissant",
        restaurantSlug: "cafe-xyz",
        categoryId: "desserts",
        name: "Almond Croissant",
        description: "Twice-baked, with frangipane still warm.",
        ingredients: ["Butter pastry", "Almond cream", "Icing sugar"],
        price: 180,
        image: unsplash("photo-1509440159596-0249088772ff"),
        diet: "veg",
        available: true,
        popular: true,
      },
      {
        id: "banana-bread",
        restaurantSlug: "cafe-xyz",
        categoryId: "desserts",
        name: "Banana Bread",
        description: "Toasted, with cultured butter.",
        ingredients: ["Banana", "Walnut", "Brown butter"],
        price: 140,
        image: unsplash("photo-1605286978633-2dec93ff88a2"),
        diet: "veg",
        available: false,
      },
      {
        id: "xyz-basque",
        restaurantSlug: "cafe-xyz",
        categoryId: "desserts",
        name: "Burnt Basque Slice",
        description: "A small slice of the afternoon.",
        ingredients: ["Cream cheese", "Cream", "Vanilla"],
        price: 220,
        image: unsplash("photo-1533134486753-c833f0ed4866"),
        diet: "veg",
        available: true,
      },
      {
        id: "latte-croissant-combo",
        restaurantSlug: "cafe-xyz",
        categoryId: "combos",
        name: "Latte & Croissant",
        description: "The morning pair. Save ₹40.",
        ingredients: ["Oat Latte", "Almond Croissant"],
        price: 350,
        image: unsplash("photo-1495474472287-4d71bcdd2085"),
        diet: "veg",
        available: true,
        popular: true,
        tags: ["Save ₹40"],
      },
    ],
  },
];

export const restaurantMap = Object.fromEntries(
  restaurants.map((restaurant) => [restaurant.slug, restaurant]),
) as Record<string, Restaurant>;
